### ISSUE TITLE
detailed plan and timeline

### ISSUE THREAD

**Issue by mbjones** [NCEAS/vegbank2#7]
As part of our Kickoff Epic #6, the contract calls for a detailed plan and timeline to be developed that formally extends the planning document that we already have for the project phases:

- https://github.com/NCEAS/vegbank2/blob/develop/vegbank2-plans.md

To complete this:

- [ ] Create Epic issues for each of the product release phases
- [ ] Move all tasks from that document with time estimates to this project board as issues, and associate them with the appropriate Epic and Deliverable labels
- [ ] Re-evaluate other development activities as needed
- [ ] Plan quarterly release timeline for incremental product releases for all deliverables

**Comment by mbjones** [comment]
@regetz turning this one over to you to update progress and likely close if we are done with it.

**Comment by mbjones** [comment]
@regetz can this be closed now?

**Comment by regetz** [comment]
We shared and reviewed a timeline & plan (as an external document) with the stakeholder team. As we get things better organized here in GitHub, the [VegBank Project](https://github.com/orgs/NCEAS/projects/23) should ultimately serve as the source as truth around planning & scheduling.
